### ISSUE TITLE
sc_functions are not available

### ISSUE THREAD

**Issue by danielruss** [neurojacob/blum_et_al_2020#1]
Hi Jacob,
   Since you used the line
`source('/oak/stanford/groups/agitler/Jacob/single_cell_motor_neurons/seurat_analysis_scripts/sc_functions.R')`
I cannot run your example since I dont have access to your /oak disk.  Can you turn on Github pages and put your sc_functions.R file in github so we can load it like 
`source('neurojacab.github.io/blum_et_al_2021/sc_functions.R')`
If you have any questions on how to do this, I'm happy to help.

**Comment by neurojacob** [comment]
Ah! Thank you for pointing that out. Just uploaded sc_functions.R, please let me know if that resolved the issue.

**Comment by danielruss** [comment]
That works.  Thank you
